POST http://localhost:4000/app/signUpData
Content-Type: application/json

{
    "fullName": "trial fullName",
    "email": "trial email",
    "password": "trial Password",
    "gender": "trial gender",
    "dob": "trial dob",
    "mobile": "trial mobile"
}
###
POST http://localhost:4000/app/loginData
Content-Type: application/json

{
    "loginId": "1231231231",
    "loginPassword": "123123123"
}
###
###
POST http://localhost:4000/app/resetpasscode
Content-Type: application/json

{
    "loginId": "1234567891",
    "password": "godblessyou"
}
###
POST http://localhost:4000/app/createapp
Content-Type: application/json

{
      "applicationType": "provider",
      "applicantName": "Dilan M",
      "applicantMobile": "9952865234",
      "companyDetails": "YesDil pvt. Ltd., Tuticorin",
      "vacancyCount": "12",
      "workDetails": "2asdad",
      "qualifications": ["diploma","graduate"],
      "bookedBy": "1234567891"
}
###
POST http://localhost:4000/app/createapp
Content-Type: application/json

{
      "applicationType": "seeker",
      "applicantName": "Dilan M",
      "applicantMobile": "9952865234",
      "age": "33",
      "address": "26,Railway station road, tuticorin-628001.",
      "qualification": "less than or equal to 8th",
      "preferenceOne": "Marketing",
      "preferenceTwo": "Human resources(HR)",
      "bookedBy": "1234567891"
}
###
POST http://localhost:4000/app/createadmin
Content-Type: application/json

{
    "adminName":"testadmin2",
    "adminId":"2512251201",
    "adminPwd":"adminpwd1"
}
###
GET http://localhost:4000/app/getmyrequests
Content-Type: application/json

{
      "loginId": "1231231231"
}
###
GET http://localhost:4000/app/getallrequests
Content-Type: application/json

{
      "loginId": "2512251200"
}
###
